/**
 * 주소의 시·군·구를 언어별 표기로 바꿉니다.
 *
 * 시/도는 `region` enum 이라 messages 의 `region` 네임스페이스가 번역하지만,
 * 그 아래 시·군·구는 자유 문자열이라 번역할 방법이 없었습니다. 그래서 같은 시 안에서
 * 이사하면 "대구 → 대구" 처럼 출발지와 도착지가 구분되지 않았습니다.
 *
 * 번역 API 를 쓰지 않습니다 — 고유명사라 의미 번역되면 오히려 틀리고(테헤란로 →
 * "Tehran Road"), 목록을 열 때마다 호출이 수십 건씩 나갑니다. 행정구역은 거의 바뀌지
 * 않아서 표를 들고 있는 쪽이 정확하고 비용도 들지 않습니다.
 */

/** 한국어는 원문을 그대로 쓰므로 번역 대상 언어만 둡니다 */
const TRANSLATED_LOCALES = ["en", "ja", "zh"] as const;
type TranslatedLocale = (typeof TRANSLATED_LOCALES)[number];

/** 접미사는 어간과 따로 둡니다 — "강남"+"구" 조합이라 206개 × 3종이 됩니다 */
const DISTRICT_SUFFIXES: Record<string, Record<TranslatedLocale, string>> = {
  구: { en: "-gu", ja: "区", zh: "区" },
  시: { en: "-si", ja: "市", zh: "市" },
  군: { en: "-gun", ja: "郡", zh: "郡" },
};

// 시·군·구 이름(접미사 제외)의 언어별 표기.
//
// en 은 국어의 로마자 표기법, ja 는 신자체, zh 는 간체자입니다.
// 같은 이름이 여러 시·도에 있어도(중구는 6곳) 표기는 같아서 이름만 키로 둡니다.
const DISTRICT_STEMS: Record<string, Record<TranslatedLocale, string>> = {
  가평: { en: "Gapyeong", ja: "加平", zh: "加平" },
  강남: { en: "Gangnam", ja: "江南", zh: "江南" },
  강동: { en: "Gangdong", ja: "江東", zh: "江东" },
  강릉: { en: "Gangneung", ja: "江陵", zh: "江陵" },
  강북: { en: "Gangbuk", ja: "江北", zh: "江北" },
  강서: { en: "Gangseo", ja: "江西", zh: "江西" },
  강진: { en: "Gangjin", ja: "康津", zh: "康津" },
  강화: { en: "Ganghwa", ja: "江華", zh: "江华" },
  거제: { en: "Geoje", ja: "巨済", zh: "巨济" },
  거창: { en: "Geochang", ja: "居昌", zh: "居昌" },
  경산: { en: "Gyeongsan", ja: "慶山", zh: "庆山" },
  경주: { en: "Gyeongju", ja: "慶州", zh: "庆州" },
  계룡: { en: "Gyeryong", ja: "鶏龍", zh: "鸡龙" },
  계양: { en: "Gyeyang", ja: "桂陽", zh: "桂阳" },
  고령: { en: "Goryeong", ja: "高霊", zh: "高灵" },
  고성: { en: "Goseong", ja: "高城", zh: "高城" },
  고양: { en: "Goyang", ja: "高陽", zh: "高阳" },
  고창: { en: "Gochang", ja: "高敞", zh: "高敞" },
  고흥: { en: "Goheung", ja: "高興", zh: "高兴" },
  곡성: { en: "Gokseong", ja: "谷城", zh: "谷城" },
  공주: { en: "Gongju", ja: "公州", zh: "公州" },
  과천: { en: "Gwacheon", ja: "果川", zh: "果川" },
  관악: { en: "Gwanak", ja: "冠岳", zh: "冠岳" },
  광명: { en: "Gwangmyeong", ja: "光明", zh: "光明" },
  광산: { en: "Gwangsan", ja: "光山", zh: "光山" },
  광양: { en: "Gwangyang", ja: "光陽", zh: "光阳" },
  광주: { en: "Gwangju", ja: "広州", zh: "广州" },
  광진: { en: "Gwangjin", ja: "広津", zh: "广津" },
  괴산: { en: "Goesan", ja: "槐山", zh: "槐山" },
  구례: { en: "Gurye", ja: "求礼", zh: "求礼" },
  구로: { en: "Guro", ja: "九老", zh: "九老" },
  구리: { en: "Guri", ja: "九里", zh: "九里" },
  구미: { en: "Gumi", ja: "亀尾", zh: "龟尾" },
  군산: { en: "Gunsan", ja: "群山", zh: "群山" },
  군위: { en: "Gunwi", ja: "軍威", zh: "军威" },
  군포: { en: "Gunpo", ja: "軍浦", zh: "军浦" },
  금산: { en: "Geumsan", ja: "錦山", zh: "锦山" },
  금정: { en: "Geumjeong", ja: "金井", zh: "金井" },
  금천: { en: "Geumcheon", ja: "衿川", zh: "衿川" },
  기장: { en: "Gijang", ja: "機張", zh: "机张" },
  김제: { en: "Gimje", ja: "金堤", zh: "金堤" },
  김천: { en: "Gimcheon", ja: "金泉", zh: "金泉" },
  김포: { en: "Gimpo", ja: "金浦", zh: "金浦" },
  김해: { en: "Gimhae", ja: "金海", zh: "金海" },
  나주: { en: "Naju", ja: "羅州", zh: "罗州" },
  남: { en: "Nam", ja: "南", zh: "南" },
  남동: { en: "Namdong", ja: "南洞", zh: "南洞" },
  남양주: { en: "Namyangju", ja: "南楊州", zh: "南杨州" },
  남원: { en: "Namwon", ja: "南原", zh: "南原" },
  남해: { en: "Namhae", ja: "南海", zh: "南海" },
  노원: { en: "Nowon", ja: "蘆原", zh: "芦原" },
  논산: { en: "Nonsan", ja: "論山", zh: "论山" },
  단양: { en: "Danyang", ja: "丹陽", zh: "丹阳" },
  달서: { en: "Dalseo", ja: "達西", zh: "达西" },
  달성: { en: "Dalseong", ja: "達城", zh: "达城" },
  담양: { en: "Damyang", ja: "潭陽", zh: "潭阳" },
  당진: { en: "Dangjin", ja: "唐津", zh: "唐津" },
  대덕: { en: "Daedeok", ja: "大德", zh: "大德" },
  도봉: { en: "Dobong", ja: "道峰", zh: "道峰" },
  동: { en: "Dong", ja: "東", zh: "东" },
  동대문: { en: "Dongdaemun", ja: "東大門", zh: "东大门" },
  동두천: { en: "Dongducheon", ja: "東豆川", zh: "东豆川" },
  동래: { en: "Dongnae", ja: "東萊", zh: "东莱" },
  동작: { en: "Dongjak", ja: "銅雀", zh: "铜雀" },
  동해: { en: "Donghae", ja: "東海", zh: "东海" },
  마포: { en: "Mapo", ja: "麻浦", zh: "麻浦" },
  목포: { en: "Mokpo", ja: "木浦", zh: "木浦" },
  무안: { en: "Muan", ja: "務安", zh: "务安" },
  무주: { en: "Muju", ja: "茂朱", zh: "茂朱" },
  문경: { en: "Mungyeong", ja: "聞慶", zh: "闻庆" },
  미추홀: { en: "Michuhol", ja: "弥鄒忽", zh: "弥邹忽" },
  밀양: { en: "Miryang", ja: "密陽", zh: "密阳" },
  보령: { en: "Boryeong", ja: "保寧", zh: "保宁" },
  보성: { en: "Boseong", ja: "宝城", zh: "宝城" },
  보은: { en: "Boeun", ja: "報恩", zh: "报恩" },
  봉화: { en: "Bonghwa", ja: "奉化", zh: "奉化" },
  부산진: { en: "Busanjin", ja: "釜山鎮", zh: "釜山镇" },
  부안: { en: "Buan", ja: "扶安", zh: "扶安" },
  부여: { en: "Buyeo", ja: "扶余", zh: "扶余" },
  부천: { en: "Bucheon", ja: "富川", zh: "富川" },
  부평: { en: "Bupyeong", ja: "富平", zh: "富平" },
  북: { en: "Buk", ja: "北", zh: "北" },
  사상: { en: "Sasang", ja: "沙上", zh: "沙上" },
  사천: { en: "Sacheon", ja: "泗川", zh: "泗川" },
  사하: { en: "Saha", ja: "沙下", zh: "沙下" },
  산청: { en: "Sancheong", ja: "山清", zh: "山清" },
  삼척: { en: "Samcheok", ja: "三陟", zh: "三陟" },
  상주: { en: "Sangju", ja: "尚州", zh: "尚州" },
  서: { en: "Seo", ja: "西", zh: "西" },
  서귀포: { en: "Seogwipo", ja: "西帰浦", zh: "西归浦" },
  서대문: { en: "Seodaemun", ja: "西大門", zh: "西大门" },
  서산: { en: "Seosan", ja: "瑞山", zh: "瑞山" },
  서천: { en: "Seocheon", ja: "舒川", zh: "舒川" },
  서초: { en: "Seocho", ja: "瑞草", zh: "瑞草" },
  성남: { en: "Seongnam", ja: "城南", zh: "城南" },
  성동: { en: "Seongdong", ja: "城東", zh: "城东" },
  성북: { en: "Seongbuk", ja: "城北", zh: "城北" },
  성주: { en: "Seongju", ja: "星州", zh: "星州" },
  속초: { en: "Sokcho", ja: "束草", zh: "束草" },
  송파: { en: "Songpa", ja: "松坡", zh: "松坡" },
  수성: { en: "Suseong", ja: "寿城", zh: "寿城" },
  수영: { en: "Suyeong", ja: "水営", zh: "水营" },
  수원: { en: "Suwon", ja: "水原", zh: "水原" },
  순창: { en: "Sunchang", ja: "淳昌", zh: "淳昌" },
  순천: { en: "Suncheon", ja: "順天", zh: "顺天" },
  시흥: { en: "Siheung", ja: "始興", zh: "始兴" },
  신안: { en: "Sinan", ja: "新安", zh: "新安" },
  아산: { en: "Asan", ja: "牙山", zh: "牙山" },
  안동: { en: "Andong", ja: "安東", zh: "安东" },
  안산: { en: "Ansan", ja: "安山", zh: "安山" },
  안성: { en: "Anseong", ja: "安城", zh: "安城" },
  안양: { en: "Anyang", ja: "安養", zh: "安养" },
  양구: { en: "Yanggu", ja: "楊口", zh: "杨口" },
  양산: { en: "Yangsan", ja: "梁山", zh: "梁山" },
  양양: { en: "Yangyang", ja: "襄陽", zh: "襄阳" },
  양주: { en: "Yangju", ja: "楊州", zh: "杨州" },
  양천: { en: "Yangcheon", ja: "陽川", zh: "阳川" },
  양평: { en: "Yangpyeong", ja: "楊平", zh: "杨平" },
  여수: { en: "Yeosu", ja: "麗水", zh: "丽水" },
  여주: { en: "Yeoju", ja: "驪州", zh: "骊州" },
  연수: { en: "Yeonsu", ja: "延寿", zh: "延寿" },
  연제: { en: "Yeonje", ja: "蓮堤", zh: "莲堤" },
  연천: { en: "Yeoncheon", ja: "漣川", zh: "涟川" },
  영광: { en: "Yeonggwang", ja: "霊光", zh: "灵光" },
  영덕: { en: "Yeongdeok", ja: "盈徳", zh: "盈德" },
  영도: { en: "Yeongdo", ja: "影島", zh: "影岛" },
  영동: { en: "Yeongdong", ja: "永同", zh: "永同" },
  영등포: { en: "Yeongdeungpo", ja: "永登浦", zh: "永登浦" },
  영암: { en: "Yeongam", ja: "霊岩", zh: "灵岩" },
  영양: { en: "Yeongyang", ja: "英陽", zh: "英阳" },
  영월: { en: "Yeongwol", ja: "寧越", zh: "宁越" },
  영주: { en: "Yeongju", ja: "栄州", zh: "荣州" },
  영천: { en: "Yeongcheon", ja: "永川", zh: "永川" },
  예산: { en: "Yesan", ja: "礼山", zh: "礼山" },
  예천: { en: "Yecheon", ja: "醴泉", zh: "醴泉" },
  오산: { en: "Osan", ja: "烏山", zh: "乌山" },
  옥천: { en: "Okcheon", ja: "沃川", zh: "沃川" },
  옹진: { en: "Ongjin", ja: "甕津", zh: "瓮津" },
  완도: { en: "Wando", ja: "莞島", zh: "莞岛" },
  완주: { en: "Wanju", ja: "完州", zh: "完州" },
  용산: { en: "Yongsan", ja: "龍山", zh: "龙山" },
  용인: { en: "Yongin", ja: "龍仁", zh: "龙仁" },
  울릉: { en: "Ulleung", ja: "鬱陵", zh: "郁陵" },
  울주: { en: "Ulju", ja: "蔚州", zh: "蔚州" },
  울진: { en: "Uljin", ja: "蔚珍", zh: "蔚珍" },
  원주: { en: "Wonju", ja: "原州", zh: "原州" },
  유성: { en: "Yuseong", ja: "儒城", zh: "儒城" },
  은평: { en: "Eunpyeong", ja: "恩平", zh: "恩平" },
  음성: { en: "Eumseong", ja: "陰城", zh: "阴城" },
  의령: { en: "Uiryeong", ja: "宜寧", zh: "宜宁" },
  의성: { en: "Uiseong", ja: "義城", zh: "义城" },
  의왕: { en: "Uiwang", ja: "義王", zh: "义王" },
  의정부: { en: "Uijeongbu", ja: "議政府", zh: "议政府" },
  이천: { en: "Icheon", ja: "利川", zh: "利川" },
  익산: { en: "Iksan", ja: "益山", zh: "益山" },
  인제: { en: "Inje", ja: "麟蹄", zh: "麟蹄" },
  임실: { en: "Imsil", ja: "任実", zh: "任实" },
  장성: { en: "Jangseong", ja: "長城", zh: "长城" },
  장수: { en: "Jangsu", ja: "長水", zh: "长水" },
  장흥: { en: "Jangheung", ja: "長興", zh: "长兴" },
  전주: { en: "Jeonju", ja: "全州", zh: "全州" },
  정선: { en: "Jeongseon", ja: "旌善", zh: "旌善" },
  정읍: { en: "Jeongeup", ja: "井邑", zh: "井邑" },
  제주: { en: "Jeju", ja: "済州", zh: "济州" },
  제천: { en: "Jecheon", ja: "堤川", zh: "堤川" },
  종로: { en: "Jongno", ja: "鐘路", zh: "钟路" },
  중: { en: "Jung", ja: "中", zh: "中" },
  중랑: { en: "Jungnang", ja: "中浪", zh: "中浪" },
  증평: { en: "Jeungpyeong", ja: "曽坪", zh: "曾坪" },
  진도: { en: "Jindo", ja: "珍島", zh: "珍岛" },
  진안: { en: "Jinan", ja: "鎮安", zh: "镇安" },
  진주: { en: "Jinju", ja: "晋州", zh: "晋州" },
  진천: { en: "Jincheon", ja: "鎮川", zh: "镇川" },
  창녕: { en: "Changnyeong", ja: "昌寧", zh: "昌宁" },
  창원: { en: "Changwon", ja: "昌原", zh: "昌原" },
  천안: { en: "Cheonan", ja: "天安", zh: "天安" },
  철원: { en: "Cheorwon", ja: "鉄原", zh: "铁原" },
  청도: { en: "Cheongdo", ja: "清道", zh: "清道" },
  청송: { en: "Cheongsong", ja: "青松", zh: "青松" },
  청양: { en: "Cheongyang", ja: "青陽", zh: "青阳" },
  청주: { en: "Cheongju", ja: "清州", zh: "清州" },
  춘천: { en: "Chuncheon", ja: "春川", zh: "春川" },
  충주: { en: "Chungju", ja: "忠州", zh: "忠州" },
  칠곡: { en: "Chilgok", ja: "漆谷", zh: "漆谷" },
  태백: { en: "Taebaek", ja: "太白", zh: "太白" },
  태안: { en: "Taean", ja: "泰安", zh: "泰安" },
  통영: { en: "Tongyeong", ja: "統営", zh: "统营" },
  파주: { en: "Paju", ja: "坡州", zh: "坡州" },
  평창: { en: "Pyeongchang", ja: "平昌", zh: "平昌" },
  평택: { en: "Pyeongtaek", ja: "平沢", zh: "平泽" },
  포천: { en: "Pocheon", ja: "抱川", zh: "抱川" },
  포항: { en: "Pohang", ja: "浦項", zh: "浦项" },
  하남: { en: "Hanam", ja: "河南", zh: "河南" },
  하동: { en: "Hadong", ja: "河東", zh: "河东" },
  함안: { en: "Haman", ja: "咸安", zh: "咸安" },
  함양: { en: "Hamyang", ja: "咸陽", zh: "咸阳" },
  함평: { en: "Hampyeong", ja: "咸平", zh: "咸平" },
  합천: { en: "Hapcheon", ja: "陜川", zh: "陕川" },
  해남: { en: "Haenam", ja: "海南", zh: "海南" },
  해운대: { en: "Haeundae", ja: "海雲台", zh: "海云台" },
  홍성: { en: "Hongseong", ja: "洪城", zh: "洪城" },
  홍천: { en: "Hongcheon", ja: "洪川", zh: "洪川" },
  화성: { en: "Hwaseong", ja: "華城", zh: "华城" },
  화순: { en: "Hwasun", ja: "和順", zh: "和顺" },
  화천: { en: "Hwacheon", ja: "華川", zh: "华川" },
  횡성: { en: "Hoengseong", ja: "横城", zh: "横城" },
};
/**
 * "강남구" → "Gangnam-gu" / "江南区". 표에 없으면 `null` 을 돌려줍니다.
 *
 * 모르는 이름을 한글 그대로 내보내면 "Seoul 어딘가구" 처럼 두 언어가 섞여서,
 * 호출부가 시/도만 보여주는 쪽을 고를 수 있게 `null` 로 알립니다.
 */
export function translateDistrict(district: string, locale: string): string | null {
  if (locale === "ko") return district;
  if (!TRANSLATED_LOCALES.includes(locale as TranslatedLocale)) return null;

  const key = locale as TranslatedLocale;
  const suffix = DISTRICT_SUFFIXES[district.at(-1) ?? ""];
  const stem = DISTRICT_STEMS[district.slice(0, -1)];
  if (!suffix || !stem) return null;

  return stem[key] + suffix[key];
}
