// BE `ERROR_CODES`와 동일한 값 — 사용자에게 보여줄 문구가 필요한 코드를 전부 둔다.
// BE 쪽 `src/common/errors/errorCodes.ts` 와 1:1 입니다. 한쪽만 늘리면 번역이 비어
// 호출부 기본 문구로 떨어지므로, BE에 코드가 추가되면 여기와 `messages/*.json` 을 같이 채우세요.
export const AUTH_ERROR_CODES = {
  // 인증 / 권한
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PROFILE_REQUIRED: "PROFILE_REQUIRED",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  INVALID_OAUTH_CODE: "INVALID_OAUTH_CODE",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  INVALID_OR_EXPIRED_SIGNUP_TOKEN: "INVALID_OR_EXPIRED_SIGNUP_TOKEN",
  PROVIDER_ACCOUNT_ALREADY_LINKED: "PROVIDER_ACCOUNT_ALREADY_LINKED",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",

  // 비밀번호 재설정
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_ATTEMPTS_EXCEEDED: "RESET_CODE_ATTEMPTS_EXCEEDED",
  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",
  // 프로필 수정 진입 이메일 인증 (#131) — 비밀번호 재설정 코드와는 별개 흐름
  INVALID_PROFILE_EDIT_CODE: "INVALID_PROFILE_EDIT_CODE",
  PROFILE_EDIT_CODE_EXPIRED: "PROFILE_EDIT_CODE_EXPIRED",
  PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED: "PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED",
  // 계정 정보 수정 요청 시 최근 30분 이내 이메일 인증이 없을 때 BE가 내려주는 403 — 인증 화면을 다시 띄운다
  PROFILE_EDIT_VERIFICATION_REQUIRED: "PROFILE_EDIT_VERIFICATION_REQUIRED",

  // 견적 요청
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REQUEST_EXISTS",
  NO_ACTIVE_REQUEST: "NO_ACTIVE_REQUEST",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ALREADY_TARGETED: "ALREADY_TARGETED",

  // 견적
  ESTIMATE_LIMIT_EXCEEDED: "ESTIMATE_LIMIT_EXCEEDED",
  ALREADY_ESTIMATED: "ALREADY_ESTIMATED",
  NOT_SERVICE_REGION: "NOT_SERVICE_REGION",
  ESTIMATE_ALREADY_PROCESSED: "ESTIMATE_ALREADY_PROCESSED",
  ESTIMATE_NOT_COMPLETED: "ESTIMATE_NOT_COMPLETED",
  ALREADY_PAID: "ALREADY_PAID",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REQUEST_ALREADY_SENT: "PAYMENT_REQUEST_ALREADY_SENT",
  DEPOSIT_NOT_REQUIRED: "DEPOSIT_NOT_REQUIRED",
  DEPOSIT_EXPIRED: "DEPOSIT_EXPIRED",
  DEPOSIT_NOT_PAID: "DEPOSIT_NOT_PAID",
  EXTRA_CHARGE_ALREADY_REQUESTED: "EXTRA_CHARGE_ALREADY_REQUESTED",
  EXTRA_CHARGE_TOO_LARGE: "EXTRA_CHARGE_TOO_LARGE",
  EXTRA_CHARGE_NOT_PENDING: "EXTRA_CHARGE_NOT_PENDING",
  EXTRA_CHARGE_PENDING: "EXTRA_CHARGE_PENDING",

  // 리뷰 / 찜
  REVIEW_ALREADY_CONFIRMED: "REVIEW_ALREADY_CONFIRMED",
  ALREADY_FAVORITED: "ALREADY_FAVORITED",

  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  BOT_CHECK_FAILED: "BOT_CHECK_FAILED",
  CONCURRENT_REQUEST_CONFLICT: "CONCURRENT_REQUEST_CONFLICT",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
