// BE `ERROR_CODES`와 동일한 값 — FE에서 분기 처리가 필요한 코드만 선별해서 둔다.
export const AUTH_ERROR_CODES = {
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_ATTEMPTS_EXCEEDED: "RESET_CODE_ATTEMPTS_EXCEEDED",
  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",
  // 프로필 수정 진입 이메일 인증 (#131) — 비밀번호 재설정 코드와는 별개 흐름
  INVALID_PROFILE_EDIT_CODE: "INVALID_PROFILE_EDIT_CODE",
  PROFILE_EDIT_CODE_EXPIRED: "PROFILE_EDIT_CODE_EXPIRED",
  PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED: "PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
