// BE `ERROR_CODES`와 동일한 값 — 사용자에게 보여줄 문구가 필요한 코드를 전부 둔다.
// BE 쪽 `src/common/errors/errorCodes.ts` 와 1:1 입니다. 한쪽만 늘리면 번역이 비어
// 호출부 기본 문구로 떨어지므로, BE에 코드가 추가되면 여기와 `messages/*.json` 을 같이 채우세요.
export const AUTH_ERROR_CODES = {
  // 인증 / 권한
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PROFILE_REQUIRED: "PROFILE_REQUIRED",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  INVALID_OAUTH_CODE: "INVALID_OAUTH_CODE",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  INVALID_OR_EXPIRED_SIGNUP_TOKEN: "INVALID_OR_EXPIRED_SIGNUP_TOKEN",
  PROVIDER_ACCOUNT_ALREADY_LINKED: "PROVIDER_ACCOUNT_ALREADY_LINKED",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",

  // 비밀번호 재설정
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_ATTEMPTS_EXCEEDED: "RESET_CODE_ATTEMPTS_EXCEEDED",
  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",

  // 견적 요청
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REQUEST_EXISTS",
  NO_ACTIVE_REQUEST: "NO_ACTIVE_REQUEST",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ALREADY_TARGETED: "ALREADY_TARGETED",

  // 견적
  ESTIMATE_LIMIT_EXCEEDED: "ESTIMATE_LIMIT_EXCEEDED",
  ALREADY_ESTIMATED: "ALREADY_ESTIMATED",
  NOT_SERVICE_REGION: "NOT_SERVICE_REGION",
  ESTIMATE_ALREADY_PROCESSED: "ESTIMATE_ALREADY_PROCESSED",

  // 리뷰 / 찜
  REVIEW_ALREADY_CONFIRMED: "REVIEW_ALREADY_CONFIRMED",
  ALREADY_FAVORITED: "ALREADY_FAVORITED",

  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  BOT_CHECK_FAILED: "BOT_CHECK_FAILED",
  CONCURRENT_REQUEST_CONFLICT: "CONCURRENT_REQUEST_CONFLICT",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
